config/routes.rb
Rails.application.routes.draw do
  resources :teachers, only: [:new, :create, :edit, :update, :show]
  resources :students, only: [:new, :create, :edit, :update, :show] do
    resources :grades, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :parents, only: [:new, :create, :edit, :update, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit, :update, :show]
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new
    can :manage, :all if user.teacher?
    cannot :read, Parent if user.teacher?
    can :read, Student if user.personable_type == "Student"
    can :read, Parent if user.personable_type == "Parent"


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :student
end

app/models/parent.rb
class Parent < ApplicationRecord
  belongs_to :student
  has_one :user, as: :personable
  validates :full_name, presence: true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :teacher
  has_many :parents
  has_many :grades
  has_one :user, as: :personable
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :students
  has_one :user, as: :personable
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :personable, polymorphic: true
  validates :email, uniqueness: true

  def password=(unhashed_password)
    @_password = BCrypt::Password.create(unhashed_password)
    self.password_hash = @_password
  end

  def password
    @_password ||= BCrypt::Password.new(password_hash)
  end

  def teacher?
    self.personable_type == "Teacher"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
     User.find_by(id: session["current_user_id"])
  end

  rescue_from CanCan::AccessDenied do |error|
    redirect_to root_path, flash: {danger: error.message}
  end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  load_and_authorize_resource

  def new
    @student = Student.find(params[:student_id])
    @grade = Grade.new()
  end

  def create
    @student = Student.find(params[:student_id])
    @grade = @student.grades.new(grade_params)
    if @grade.save
      redirect_to @student
    else
      render :new
    end
  end

  def edit
    @grade = Grade.find(params[:id])
  end

  def update
    @grade = Grade.find(params[:id])
    if @grade.update(grade_params)
      redirect_to @grade.student
    else
      render :edit
    end
  end

  def grade_params
    params.require(:grade).permit(:assignment_name, :due_at, :value)
  end

  def destroy
    Grade.find(params[:id]).destroy
    redirect_to Student.find(params[:student_id])
  end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  load_and_authorize_resource

  def new
    @student = Student.find(params["student_id"])
    @parent = Parent.new()
  end

  def create
    @student = Student.find(params["parent"]["student_id"])
    @parent = @student.parents.build(parent_params)
    if @parent.save
      redirect_to teacher_path(current_user.personable_id)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def show
  end

  def parent_params
    params.require(:parent).permit(:full_name, :email)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
      @user = User.find_by(email: params[:email])
      if @user && @user.password == params[:password]
        session["current_user_id"] = @user.id
        path_redirect(@user.personable_id, @user.personable_type)
      else
        @message = "You username or password was not correct"
        render :new
      end
    end

    def destroy
      session.delete("current_user_id")
      redirect_to root_path
    end

    def path_redirect(id, personable_type)
      redirect_to send("#{personable_type.downcase}_path", id)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  load_and_authorize_resource

  def new
    @student = Student.new()
  end

  def create
    @student = Student.new(student_params)
    @student.teacher = current_user.personable
    if @student.save
      redirect_to teacher_path(current_user.personable_id)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def show
  end

  def student_params
    params.require(:student).permit(:full_name, :email)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  load_and_authorize_resource
  
  def new
    @teacher = Teacher.new()
  end

  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      redirect_to teacher_path(current_user.personable_id)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def show
  end

  def teacher_params
    params.require(:teacher).permit(:full_name, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)
    @user.personable = find_person if find_person
    if !find_person
      flash[:danger] = "You have not been added to the roster yet"
      redirect_to root_path
    elsif @user.save
      session["current_user_id"] = @user.id
      redirect_to @user.personable
    else
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def find_person
    Student.find_by(email: params[:user][:email]) || Parent.find_by(email: params[:user][:email]) || Teacher.find_by(email: params[:user][:email])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      redirect_to current_user
    else
      render :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/grades/_list.html.erb
<table class="table">
  <tr>
    <th>
      Assignment
    </th>
    <th>
      Grade
    </th>
    <th>
      Due Date
    </th>
    <% student.grades.each do |grade| %>
    <tr>
      <td>
        <%= grade.assignment_name %>
      </td>
      <td>
        <%= grade.value %>
      </td>
      <td>
        <%= grade.due_at %>
      </td>
    </tr>
    <% end %>
  </tr>
</table>

app/views/grades/edit.html.erb
<h1>Grades#edit</h1>
<p>Find me in app/views/grades/edit.html.erb</p>

app/views/grades/new.html.erb
<h1>New Grade</h1>
<%= form_for([@student, @grade]) do |f| %>
  <div class="form-group">
    <%= f.label :assignment_name %>
    <%= f.text_field :assignment_name, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :value %>
    <%= f.text_field :value, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :due_at %>
    <%= f.date_field :due_at, class: "form-control" %>
  </div>

  <%= f.submit "Add", class: "btn btn-primary" %>

<% end %>

app/views/parents/edit.html.erb
<h1>Parents#edit</h1>
<p>Find me in app/views/parents/edit.html.erb</p>

app/views/parents/new.html.erb
<h1>Add a parent for <%= @student.full_name %></h1>
<%= form_for @parent do |f| %>
  <div class="form-group">
    <%= f.label :full_name %>
    <%= f.text_field :full_name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class:"form-control" %>
  </div>
  <%= f.hidden_field :student_id, value: @student.id %>
  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/parents/show.html.erb
<h1>Parent Portal</h1>
<h3><%= current_user.personable.student.full_name %>'s Info </h3>
<h4>Grades</h4>
<%= render partial: "grades/list", locals: {student: current_user.personable.student}%>

app/views/students/_profile.html.erb
<h1>Student Portal <small><%= @student.full_name %></small></h1>
<h4>Grades</h4>
<%= render partial: "grades/list", locals: {student: @student} %>

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

app/views/students/new.html.erb
<h1>New Student</h1>
<%= form_for @student do |f| %>
  <div class="form-group">
    <%= f.label :full_name %>
    <%= f.text_field :full_name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class:"form-control" %>
  </div>
  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/students/show.html.erb
<% if current_user.personable_type == "Student" %>
  <%= render "profile" %>
<% else %>
  <h1><%= @student.full_name %>'s Info</h1>
  <div class="row">
    <h4>Grades</h4>
    <%= link_to "Add Grade", new_student_grade_path(@student.id) %>
    <%= render partial: "grades/list", locals: {student: @student} %>
  </div>
  <div class="row">
    <h4>Parents</h4>
    <%= link_to "Add Parent", new_parent_path(student_id: @student.id) %>
    <table class="table">
      <tr>
        <th>
          Parent Name
        </th>
        <th>
          Parent Email
        </th>
      </tr>
      <% @student.parents.each do |parent| %>
        <tr>
          <td>
            <%= parent.full_name %>
          </td>
          <td>
            <%= parent.email %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="row">
    <%= link_to "All Students", teacher_path(@student.teacher.id), class:"btn btn-primary" %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Teachers#edit</h1>
<p>Find me in app/views/teachers/edit.html.erb</p>

app/views/teachers/new.html.erb
<h1>Teachers#new</h1>
<p>Find me in app/views/teachers/new.html.erb</p>

app/views/teachers/show.html.erb
<h1>Teacher Portal</h1>
<div class="row">
  <h4>Your Students</h4>
  <%= link_to "Add Student", new_student_path, class: "btn btn-default" %>
  <ul>
    <% current_user.personable.students.each do |student| %>
      <li>
        <%= link_to student.full_name, student %>

      <% student.parents.each do |parent| %>
        <ul>
          <li>
            <%= parent.full_name %>
          </li>
        </ul>
      </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Create Login</h1>
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class:"form-control" %>
  </div>

  <%= f.submit "Save", class:"btn btn-primary" %>

<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>