config/routes.rb
Rails.application.routes.draw do
  resources :teachers, only: [:new, :create, :edit, :update, :show]
  resources :students, only: [:new, :create, :edit, :update, :show] do
    resources :grades, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :parents, only: [:new, :create, :edit, :update, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit, :update, :show]
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new
    can :manage, :all if user.teacher?
    cannot :read, Parent if user.teacher?
    can :read, Student if user.personable_type == "Student"
    can :read, Parent if user.personable_type == "Parent"


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :student
end

app/models/parent.rb
class Parent < ApplicationRecord
  belongs_to :student
  has_one :user, as: :personable
  validates :full_name, presence: true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :teacher
  has_many :parents
  has_many :grades
  has_one :user, as: :personable
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :students
  has_one :user, as: :personable
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :personable, polymorphic: true
  validates :email, uniqueness: true

  def password=(unhashed_password)
    @_password = BCrypt::Password.create(unhashed_password)
    self.password_hash = @_password
  end

  def password
    @_password ||= BCrypt::Password.new(password_hash)
  end

  def teacher?
    self.personable_type == "Teacher"
  end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  load_and_authorize_resource

  def new
    @student = Student.find(params[:student_id])
    @grade = Grade.new()
  end

  def create
    @student = Student.find(params[:student_id])
    @grade = @student.grades.new(grade_params)
    if @grade.save
      redirect_to @student
    else
      render :new
    end
  end

  def edit
    @grade = Grade.find(params[:id])
  end

  def update
    @grade = Grade.find(params[:id])
    if @grade.update(grade_params)
      redirect_to @grade.student
    else
      render :edit
    end
  end

  def grade_params
    params.require(:grade).permit(:assignment_name, :due_at, :value)
  end

  def destroy
    Grade.find(params[:id]).destroy
    redirect_to Student.find(params[:student_id])
  end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  load_and_authorize_resource

  def new
    @student = Student.find(params["student_id"])
    @parent = Parent.new()
  end

  def create
    @student = Student.find(params["parent"]["student_id"])
    @parent = @student.parents.build(parent_params)
    if @parent.save
      redirect_to teacher_path(current_user.personable_id)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def show
  end

  def parent_params
    params.require(:parent).permit(:full_name, :email)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
      @user = User.find_by(email: params[:email])
      if @user && @user.password == params[:password]
        session["current_user_id"] = @user.id
        path_redirect(@user.personable_id, @user.personable_type)
      else
        @message = "You username or password was not correct"
        render :new
      end
    end

    def destroy
      session.delete("current_user_id")
      redirect_to root_path
    end

    def path_redirect(id, personable_type)
      redirect_to send("#{personable_type.downcase}_path", id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)
    @user.personable = find_person if find_person
    if !find_person
      flash[:danger] = "You have not been added to the roster yet"
      redirect_to root_path
    elsif @user.save
      session["current_user_id"] = @user.id
      redirect_to @user.personable
    else
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def find_person
    Student.find_by(email: params[:user][:email]) || Parent.find_by(email: params[:user][:email]) || Teacher.find_by(email: params[:user][:email])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      redirect_to current_user
    else
      render :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gradebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container-fluid">
        <span class="navbar-brand">Gradebook</span>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li class="nav-item">
              <%= link_to "Logout", session_path, method: :delete, class: "nav-item nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_session_path %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |type, msg| %>
        <div class="alert alert-<%= type %>">
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>